export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SETECTED_PRODUCTS:"SETECTED_PRODUCTS",

    // REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    SORT_PRICE_H_TO_L:"SORT_PRICE_H_TO_L",
    SORT_PRICE_L_TO_H:"SORT_PRICE_L_TO_H",
    SORT_BY_WOMEN:"SORT_BY_WOMEN",
    SORT_BY_MEN:"SORT_BY_MEN",

    SORT_RATING_L_TO_H:"SORT_RATING_L_TO_H",
    SORT_RATING_H_TO_L:"SORT_RATING_H_TO_L",
    SORT_NAME_ASS:"SORT_NAME_ASS",
    SORT_NAME_DISS:"SORT_NAME_DISS",
        
    LOGIN_LOADING:"LOGIN_LOADING",
    LOGIN_ERROR:"LOGIN_ERROR",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",


    REGISTER_LOADING:"REGISTER_LOADING",
    REGISTER_ERROR:"REGISTER_ERROR",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",


    CART_ITMES:"CART_ITEMS",


    ADD_TO_CART:"ADD_TO_CART",

    FETCH_PRODUCT_DETAILS:"FETCH_PRODUCT_DETAILS",


    ADD_ADDRESS:"ADD_ADDRESS",

    FETCH_ADDRESS:"FETCH_ADDRESS"
    
}
