export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SETECTED_PRODUCTS:"SETECTED_PRODUCTS",

    // REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    SORT_PRICE_H_TO_L:"SORT_PRICE_H_TO_L",
    SORT_PRICE_L_TO_H:"SORT_PRICE_L_TO_H",
    SORT_BY_WOMEN:"SORT_BY_WOMEN",
    SORT_BY_MEN:"SORT_BY_MEN",

}
